#!/bin/bash
#
# This example shows how you can use the THREADPOOL
# queue run a long running function that will block
# the Task Queues
# We will switch from the MAIN queue to the THREADPOOL
# queue, then execute the function, and then swap back
#
Q=THREADPOOL

echo "I'm going to simulate executing a long running blocking function."
echo "A function like this does not call co_await. It will stall the"
echo "entire queue process."
echo ""
echo "This first call will likely block everything"
echo "and make the program unresponsive for 5 seconds"
sleep 1
echo "3"
sleep 1
echo "2"
sleep 1
echo "1"
sleep 1
echo "BLOCKED"
sleep 1
blocking_sleep 5
echo "I'm awake now!"

echo "Now I'm going to call this on the THREADPOOL QUEUE"
echo "I am on queue: ${QUEUE}, switching to ${Q}"
yield $Q
echo "I am on queue: ${QUEUE}. Blocking the queue for 10 seconds. You should still be able to interact with the application"
sleep 1
blocking_sleep 10
echo "Finished blocking! Switching to MAIN"
yield MAIN
echo "I am on queue: ${QUEUE}"


