#!/bin/bash

echo "Pre-if"

if test -d /bin ; then
    echo /bin exists and is a directory
    if test -f /etc/profile ; then
        echo /etc/profile exists and is a file
    fi
fi


if test "${USER}" = "bob" ; then
    echo "You are the correct user: bob"
fi

if [[ "${USER}" = "bob" ]]; then
    echo "You are the correct user: bob"
fi


if [[ ! "${USER}"  != "bob" ]]; then
    echo "You are the correct user: bob"
fi

echo "post-if"


