#!/bin/bash

echo "Pre-if"

X=4

if test $X -eq 3 ; then
    echo "is 3"
else
    echo "Not 3 or 4"
fi

if test -d /bin ; then
    echo /bin exists and is a directory
    if test -f /etc/profile ; then
        echo /etc/profile exists and is a file
    fi
fi


if test "${USER}" = "bob" ; then
    echo "You are the correct user: bob"
fi

if [[ "${USER}" = "bob" ]]; then
    echo "You are the correct user: bob"
fi


if [[ ! "${USER}"  != "bob" ]]; then
    echo "You are the correct user: bob"
fi

echo "post-if"


